<?php

return array (
  'database' => 
  array (
    'DEFAULT_CHARACTER_SET_NAME' => 'utf8mb4',
    'DEFAULT_COLLATION_NAME' => 'utf8mb4_0900_ai_ci',
  ),
  'tables' => 
  array (
    'phinxlog' => 
    array (
      'table' => 
      array (
        'table_name' => 'phinxlog',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8_general_ci',
        'character_set_name' => 'utf8',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'breakpoint' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'breakpoint',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '3',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(1)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'end_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'end_time',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'migration_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'migration_name',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '100',
          'CHARACTER_OCTET_LENGTH' => '300',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8',
          'COLLATION_NAME' => 'utf8_general_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'start_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'start_time',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'version' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'version',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'bigint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '19',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'bigint(20)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'phinxlog',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'version',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    't_calendar_uris' => 
    array (
      'table' => 
      array (
        'table_name' => 't_calendar_uris',
        'engine' => 'InnoDB',
        'table_comment' => 'Uris to ICAL calendars and friends.',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_attr' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_calendar_uris',
          'COLUMN_NAME' => 'c_attr',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Calendar attributes',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_json' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_calendar_uris',
          'COLUMN_NAME' => 'c_json',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Calendar data (json document)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_calendar_uris',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp created',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_calendar_uris',
          'COLUMN_NAME' => 'c_ts_updated',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp updated',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_calendar_uris',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_calendar_uris',
          'COLUMN_NAME' => 'c_user_id',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Creator of the calendar (account)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_user_id' => 
        array (
          1 => 
          array (
            'Table' => 't_calendar_uris',
            'Non_unique' => '1',
            'Key_name' => 'c_user_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_calendar_uris',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        't_calendar_uris_ibfk_1' => 
        array (
          'TABLE_NAME' => 't_calendar_uris',
          'COLUMN_NAME' => 'c_user_id',
          'CONSTRAINT_NAME' => 't_calendar_uris_ibfk_1',
          'REFERENCED_TABLE_NAME' => 't_core_users',
          'REFERENCED_COLUMN_NAME' => 'c_uid',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
    't_core_authn' => 
    array (
      'table' => 
      array (
        'table_name' => 't_core_authn',
        'engine' => 'InnoDB',
        'table_comment' => 'Access credentials to users defined in t_core_users. Each user is allowed a secondary name/pass combination (plausible deniability)',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_attr' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_authn',
          'COLUMN_NAME' => 'c_attr',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Object attributes (status: enabled/disabled, allowed IPs, scope - i.e. allwed/forbidden actions, rate limits, etc.)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_hash' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_authn',
          'COLUMN_NAME' => 'c_hash',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '255',
          'CHARACTER_OCTET_LENGTH' => '255',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'ascii',
          'COLLATION_NAME' => 'ascii_bin',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Password or api key hash (according to c_type)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_authn',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_modified' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_authn',
          'COLUMN_NAME' => 'c_ts_modified',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_type' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_authn',
          'COLUMN_NAME' => 'c_type',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '3',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '0 password, 1 api key',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_authn',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row/object id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_user_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_authn',
          'COLUMN_NAME' => 'c_user_uid',
          'ORDINAL_POSITION' => '7',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Corresponds to t_core_users.c_uid',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_uid' => 
        array (
          1 => 
          array (
            'Table' => 't_core_authn',
            'Non_unique' => '0',
            'Key_name' => 'c_uid',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'c_user_id' => 
        array (
          1 => 
          array (
            'Table' => 't_core_authn',
            'Non_unique' => '1',
            'Key_name' => 'c_user_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_user_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_core_authn',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        't_core_authn_ibfk_1' => 
        array (
          'TABLE_NAME' => 't_core_authn',
          'COLUMN_NAME' => 'c_user_uid',
          'CONSTRAINT_NAME' => 't_core_authn_ibfk_1',
          'REFERENCED_TABLE_NAME' => 't_core_users',
          'REFERENCED_COLUMN_NAME' => 'c_uid',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
    't_core_domains' => 
    array (
      'table' => 
      array (
        'table_name' => 't_core_domains',
        'engine' => 'InnoDB',
        'table_comment' => 'Domains (as in RBAC domains)',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_domains',
          'COLUMN_NAME' => 'c_name',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '255',
          'CHARACTER_OCTET_LENGTH' => '1020',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_0900_ai_ci',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Domain name',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_domains',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp created',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_domains',
          'COLUMN_NAME' => 'c_ts_updated',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp updated',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_domains',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_domains',
          'COLUMN_NAME' => 'c_user_id',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Creator of the domain',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_user_id' => 
        array (
          1 => 
          array (
            'Table' => 't_core_domains',
            'Non_unique' => '1',
            'Key_name' => 'c_user_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_core_domains',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        't_core_domains_ibfk_1' => 
        array (
          'TABLE_NAME' => 't_core_domains',
          'COLUMN_NAME' => 'c_user_id',
          'CONSTRAINT_NAME' => 't_core_domains_ibfk_1',
          'REFERENCED_TABLE_NAME' => 't_core_users',
          'REFERENCED_COLUMN_NAME' => 'c_uid',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
    't_core_profiles' => 
    array (
      'table' => 
      array (
        'table_name' => 't_core_profiles',
        'engine' => 'InnoDB',
        'table_comment' => 'Users\' system profiles (personal, invoicing, etc.)',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_json' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_profiles',
          'COLUMN_NAME' => 'c_json',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Profile data',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_profiles',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_users_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_profiles',
          'COLUMN_NAME' => 'c_users_uid',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Profile owner',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_core_profiles',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    't_core_users' => 
    array (
      'table' => 
      array (
        'table_name' => 't_core_users',
        'engine' => 'InnoDB',
        'table_comment' => 'Users\' table, their profile and their attributes',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_attr' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_users',
          'COLUMN_NAME' => 'c_attr',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'User\'s account attributes (enabled/disabled, GDPR anonymised, etc.)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_email' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_users',
          'COLUMN_NAME' => 'c_email',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '255',
          'CHARACTER_OCTET_LENGTH' => '1020',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_0900_ai_ci',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => 'UNI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Primary email',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_lang' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_users',
          'COLUMN_NAME' => 'c_lang',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => 'en_US',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'char',
          'CHARACTER_MAXIMUM_LENGTH' => '5',
          'CHARACTER_OCTET_LENGTH' => '20',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_0900_ai_ci',
          'COLUMN_TYPE' => 'char(5)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Preferred language',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_users',
          'COLUMN_NAME' => 'c_name',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => '255',
          'CHARACTER_OCTET_LENGTH' => '1020',
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_0900_ai_ci',
          'COLUMN_TYPE' => 'varchar(255)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'User\'s visible screen name (nickname)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_users',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp: account created',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_modified' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_users',
          'COLUMN_NAME' => 'c_ts_modified',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp: account modified',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_core_users',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '7',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row/object id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_email' => 
        array (
          1 => 
          array (
            'Table' => 't_core_users',
            'Non_unique' => '0',
            'Key_name' => 'c_email',
            'Seq_in_index' => '1',
            'Column_name' => 'c_email',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'c_screenname' => 
        array (
          1 => 
          array (
            'Table' => 't_core_users',
            'Non_unique' => '1',
            'Key_name' => 'c_screenname',
            'Seq_in_index' => '1',
            'Column_name' => 'c_name',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'c_uid' => 
        array (
          1 => 
          array (
            'Table' => 't_core_users',
            'Non_unique' => '0',
            'Key_name' => 'c_uid',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_core_users',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    't_store_items' => 
    array (
      'table' => 
      array (
        'table_name' => 't_store_items',
        'engine' => 'InnoDB',
        'table_comment' => 'Store items are just regular store items (products and one-time services for purchase)',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_attr' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_items',
          'COLUMN_NAME' => 'c_attr',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Item attributes',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_json' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_items',
          'COLUMN_NAME' => 'c_json',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Item data (json document)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_seller_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_items',
          'COLUMN_NAME' => 'c_seller_id',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Seller of this particular item',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_items',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp created',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_items',
          'COLUMN_NAME' => 'c_ts_updated',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp updated',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_items',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_seller_id' => 
        array (
          1 => 
          array (
            'Table' => 't_store_items',
            'Non_unique' => '1',
            'Key_name' => 'c_seller_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_seller_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_store_items',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        't_store_items_ibfk_1' => 
        array (
          'TABLE_NAME' => 't_store_items',
          'COLUMN_NAME' => 'c_seller_id',
          'CONSTRAINT_NAME' => 't_store_items_ibfk_1',
          'REFERENCED_TABLE_NAME' => 't_store_sellers',
          'REFERENCED_COLUMN_NAME' => 'c_uid',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
    't_store_sellers' => 
    array (
      'table' => 
      array (
        'table_name' => 't_store_sellers',
        'engine' => 'InnoDB',
        'table_comment' => 'Sellers are entities who sell stuff at specified conditions (think aliexpress or amazon sellers)',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_attr' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_sellers',
          'COLUMN_NAME' => 'c_attr',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Seller attributes',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_json' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_sellers',
          'COLUMN_NAME' => 'c_json',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Seller data (json document)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_sellers',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp created',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_sellers',
          'COLUMN_NAME' => 'c_ts_updated',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp updated',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_sellers',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_sellers',
          'COLUMN_NAME' => 'c_user_id',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Creator of the seller (account)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_user_id' => 
        array (
          1 => 
          array (
            'Table' => 't_store_sellers',
            'Non_unique' => '1',
            'Key_name' => 'c_user_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_store_sellers',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    't_store_subscriptions' => 
    array (
      'table' => 
      array (
        'table_name' => 't_store_subscriptions',
        'engine' => 'InnoDB',
        'table_comment' => 'Subscriptions are recurring purchase items (donations, memberships, internet subscriptions, periodicals delivery, etc.)',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_attr' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_subscriptions',
          'COLUMN_NAME' => 'c_attr',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Subscription attributes',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_json' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_subscriptions',
          'COLUMN_NAME' => 'c_json',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Subscription data (json document)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_seller_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_subscriptions',
          'COLUMN_NAME' => 'c_seller_id',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Seller of this particular subscription',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_subscriptions',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp created',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_subscriptions',
          'COLUMN_NAME' => 'c_ts_updated',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp updated',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_subscriptions',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_seller_id' => 
        array (
          1 => 
          array (
            'Table' => 't_store_subscriptions',
            'Non_unique' => '1',
            'Key_name' => 'c_seller_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_seller_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_store_subscriptions',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        't_store_subscriptions_ibfk_1' => 
        array (
          'TABLE_NAME' => 't_store_subscriptions',
          'COLUMN_NAME' => 'c_seller_id',
          'CONSTRAINT_NAME' => 't_store_subscriptions_ibfk_1',
          'REFERENCED_TABLE_NAME' => 't_store_sellers',
          'REFERENCED_COLUMN_NAME' => 'c_uid',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
    't_store_tickets' => 
    array (
      'table' => 
      array (
        'table_name' => 't_store_tickets',
        'engine' => 'InnoDB',
        'table_comment' => 'Tickets are time-limited booking and item offerings (tickets to conferences, workshops, merch, etc.)',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_attr' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_tickets',
          'COLUMN_NAME' => 'c_attr',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Ticket attributes',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_json' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_tickets',
          'COLUMN_NAME' => 'c_json',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Ticket data (json document)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_seller_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_tickets',
          'COLUMN_NAME' => 'c_seller_id',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Ticket seller id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_tickets',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp created',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_tickets',
          'COLUMN_NAME' => 'c_ts_updated',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp updated',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_store_tickets',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_seller_id' => 
        array (
          1 => 
          array (
            'Table' => 't_store_tickets',
            'Non_unique' => '1',
            'Key_name' => 'c_seller_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_seller_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_store_tickets',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        't_store_tickets_ibfk_1' => 
        array (
          'TABLE_NAME' => 't_store_tickets',
          'COLUMN_NAME' => 'c_seller_id',
          'CONSTRAINT_NAME' => 't_store_tickets_ibfk_1',
          'REFERENCED_TABLE_NAME' => 't_store_sellers',
          'REFERENCED_COLUMN_NAME' => 'c_uid',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
    't_worklog_items' => 
    array (
      'table' => 
      array (
        'table_name' => 't_worklog_items',
        'engine' => 'InnoDB',
        'table_comment' => 'Sellers are entities who sell stuff at specified conditions (think aliexpress or amazon sellers)',
        'table_collation' => 'utf8mb4_0900_ai_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'c_domain_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_worklog_items',
          'COLUMN_NAME' => 'c_domain_id',
          'ORDINAL_POSITION' => '1',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_json' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_worklog_items',
          'COLUMN_NAME' => 'c_json',
          'ORDINAL_POSITION' => '2',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'json',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'json',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Worklog item data (json document)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_created' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_worklog_items',
          'COLUMN_NAME' => 'c_ts_created',
          'ORDINAL_POSITION' => '3',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp created',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_ts_updated' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_worklog_items',
          'COLUMN_NAME' => 'c_ts_updated',
          'ORDINAL_POSITION' => '4',
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => '0',
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Timestamp updated',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_uid' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_worklog_items',
          'COLUMN_NAME' => 'c_uid',
          'ORDINAL_POSITION' => '5',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Unique row id',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
        'c_user_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 't_worklog_items',
          'COLUMN_NAME' => 'c_user_id',
          'ORDINAL_POSITION' => '6',
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => '10',
          'NUMERIC_SCALE' => '0',
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(10) unsigned',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => 'Creator of the worklog item (account)',
          'GENERATION_EXPRESSION' => '',
          'SRS_ID' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'c_domain_id' => 
        array (
          1 => 
          array (
            'Table' => 't_worklog_items',
            'Non_unique' => '1',
            'Key_name' => 'c_domain_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_domain_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'c_user_id' => 
        array (
          1 => 
          array (
            'Table' => 't_worklog_items',
            'Non_unique' => '1',
            'Key_name' => 'c_user_id',
            'Seq_in_index' => '1',
            'Column_name' => 'c_user_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 't_worklog_items',
            'Non_unique' => '0',
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => '1',
            'Column_name' => 'c_uid',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => 
      array (
        't_worklog_items_ibfk_1' => 
        array (
          'TABLE_NAME' => 't_worklog_items',
          'COLUMN_NAME' => 'c_user_id',
          'CONSTRAINT_NAME' => 't_worklog_items_ibfk_1',
          'REFERENCED_TABLE_NAME' => 't_core_users',
          'REFERENCED_COLUMN_NAME' => 'c_uid',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
        't_worklog_items_ibfk_2' => 
        array (
          'TABLE_NAME' => 't_worklog_items',
          'COLUMN_NAME' => 'c_domain_id',
          'CONSTRAINT_NAME' => 't_worklog_items_ibfk_2',
          'REFERENCED_TABLE_NAME' => 't_core_domains',
          'REFERENCED_COLUMN_NAME' => 'c_uid',
          'UPDATE_RULE' => 'NO ACTION',
          'DELETE_RULE' => 'CASCADE',
        ),
      ),
    ),
  ),
);